=== uo277084/SEW-Extraordinaria/XML/equipo.xsd
<?xml version="1.0" encoding="Windows-1252"?>
<xs:schema xmlns="http://tempuri.org/equipo" elementFormDefault="qualified" targetNamespace="http://tempuri.org/equipo" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="equipo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="datosEquipo" />
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="pais" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="datosEquipo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre" />
        <xs:element minOccurs="0" maxOccurs="1" ref="fechaIni" />
        <xs:element minOccurs="0" maxOccurs="1" ref="fechaFin" />
        <xs:element ref="antiguedad" />
        <xs:element ref="ciudad" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="nombre" type="xs:string" />
  <xs:element name="fechaIni">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="dia" type="xs:string" use="required" />
          <xs:attribute name="mes" type="xs:string" use="required" />
          <xs:attribute name="year" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="fechaFin">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="dia" type="xs:string" use="required" />
          <xs:attribute name="mes" type="xs:string" use="required" />
          <xs:attribute name="year" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="antiguedad" type="xs:string" />
  <xs:element name="ciudad" type="xs:string" />
  <xs:element name="pais">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="datosPais" />
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="jugador" />
      </xs:sequence>
      <xs:attribute name="nombre" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="datosPais">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="coord" />
        <xs:element ref="poblacion" />
        <xs:element ref="continente" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="coord">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="longitud" />
        <xs:element ref="latitud" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="longitud" type="xs:string" />
  <xs:element name="latitud" type="xs:string" />
  <xs:element name="poblacion" type="xs:string" />
  <xs:element name="continente" type="xs:string" />
  <xs:element name="jugador">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="datosJugador" />
        <xs:element minOccurs="0" maxOccurs="1" ref="equipo" />
        <xs:element minOccurs="0" maxOccurs="1" ref="equipo" />
      </xs:sequence>
      <xs:attribute name="nombre" type="xs:string" use="required" />
      <xs:attribute name="apellidos" type="xs:string" use="required" />
      <xs:attribute name="edad" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="datosJugador">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="fechaNac" />
        <xs:element ref="altura" />
        <xs:element ref="ciudad" />
        <xs:element ref="foto" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="fechaNac">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="dia" type="xs:string" use="required" />
          <xs:attribute name="mes" type="xs:string" use="required" />
          <xs:attribute name="year" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="altura" type="xs:string" />
  <xs:element name="foto">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="ruta" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== uo277084/SEW-Extraordinaria/XML/jugadoresEquipo.xml
<?xml version="1.0" encoding="UTF-8"?>
<equipo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="equipo.xsd">
    <datosEquipo>
        <nombre>
            Real Sporting de Gijón
        </nombre>
        <antiguedad>
            1905
        </antiguedad>
        <ciudad>
            Gijón
        </ciudad>
    </datosEquipo>
    <pais nombre="España">
        <datosPais>
            <coord>
                <longitud>
                    -3.683333
                </longitud>
                <latitud>
                    40.4
                </latitud>
            </coord>
            <poblacion>
                47,35 millones
            </poblacion>
            <continente>
                Europa
            </continente>
        </datosPais>
        <jugador nombre="Iván" apellidos="Cuéllar Sacristán" edad="37">
            <datosJugador>
                <fechaNac dia="27" mes="05" year="1984"></fechaNac>
                <altura>
                    1.87
                </altura>
                <ciudad>
                    Mérida
                </ciudad>
                <foto ruta="https://res.cloudinary.com/asw2122/image/upload/v1655033211/sew2122/cuellar.jpg"></foto>
            </datosJugador>
            <equipo>
                <datosEquipo>
                    <nombre>
                        C. D. Leganés
                    </nombre>
                    <fechas>
                        <fechaIni dia="14" mes="07" year="2017"></fechaIni>
                        <fechaFin dia="29" mes="06" year="2021"></fechaFin>
                    </fechas>
                    <antiguedad>
                        1928
                    </antiguedad>
                    <ciudad>
                        Leganés
                    </ciudad>
                </datosEquipo>
            </equipo>
            <equipo>
                <datosEquipo>
                    <nombre>
                        Real Sporting de Gijón
                    </nombre>
                    <fechas>
                        <fechaIni dia="27" mes="12" year="2008"></fechaIni>
                        <fechaFin dia="17" mes="06" year="2017"></fechaFin>
                    </fechas>
                    <antiguedad>
                        1905
                    </antiguedad>
                    <ciudad>
                        Gijón
                    </ciudad>
                </datosEquipo>
            </equipo>
        </jugador>
        <jugador nombre="Diego" apellidos="Mariño Villar" edad="32">
            <datosJugador>
                <fechaNac dia="9" mes="05" year="1990"></fechaNac>
                <altura>
                    1.85
                </altura>
                <ciudad>
                    Vigo
                </ciudad>
                <foto ruta="https://res.cloudinary.com/asw2122/image/upload/v1655033211/sew2122/diego-m.jpg"></foto>
            </datosJugador>
            <equipo>
                <datosEquipo>
                    <nombre>
                        Levante U. D.
                    </nombre>
                    <fechas>
                        <fechaIni dia="30" mes="12" year="2014"></fechaIni>
                        <fechaFin dia="04" mes="06" year="2016"></fechaFin>
                    </fechas>
                    <antiguedad>
                        1909
                    </antiguedad>
                    <ciudad>
                        Valencia
                    </ciudad>
                </datosEquipo>
            </equipo>
            <equipo>
                <datosEquipo>
                    <nombre>
                        Valladolid C. F.
                    </nombre>
                    <fechas>
                        <fechaIni dia="25" mes="06" year="2013"></fechaIni>
                        <fechaFin dia="11" mes="06" year="2014"></fechaFin>
                    </fechas>
                    <antiguedad>
                        1928
                    </antiguedad>
                    <ciudad>
                        Valladolid
                    </ciudad>
                </datosEquipo>
            </equipo>
        </jugador>
        <jugador nombre="Pedro" apellidos="Díaz Fanjul" edad="23">
            <datosJugador>
                <fechaNac dia="5" mes="06" year="1998"></fechaNac>
                <altura>
                    1.80
                </altura>
                <ciudad>
                    Gijón
                </ciudad>
                <foto ruta="https://res.cloudinary.com/asw2122/image/upload/v1655033211/sew2122/pedro-diaz.jpg"></foto>
            </datosJugador>
        </jugador>
        <jugador nombre="Jonathan" apellidos="Rodríguez Menéndez" edad="30">
            <datosJugador>
                <fechaNac dia="9" mes="07" year="1991"></fechaNac>
                <altura>
                    1.79
                </altura>
                <ciudad>
                    Cangas del Narcea
                </ciudad>
                <foto ruta="https://res.cloudinary.com/asw2122/image/upload/v1655033211/sew2122/jony.jpg"></foto>
            </datosJugador>
            <equipo>
                <datosEquipo>
                    <nombre>
                        C. A. Osasuna
                    </nombre>
                    <fechas>
                        <fechaIni dia="22" mes="08" year="2020"></fechaIni>
                        <fechaFin dia="20" mes="12" year="2021"></fechaFin>
                    </fechas>
                    <antiguedad>
                        1920
                    </antiguedad>
                    <ciudad>
                        Pamplona
                    </ciudad>
                </datosEquipo>
            </equipo>
            <equipo>
                <datosEquipo>
                    <nombre>
                        S. S. Lazio
                    </nombre>
                    <fechas>
                        <fechaIni dia="18" mes="07" year="2019"></fechaIni>
                        <fechaFin dia="09" mes="07" year="2020"></fechaFin>
                    </fechas>
                    <antiguedad>
                        1900
                    </antiguedad>
                    <ciudad>
                        Roma
                    </ciudad>
                </datosEquipo>
            </equipo>
        </jugador>
        <jugador nombre="Christian" apellidos="Rivera Hernández" edad="24">
            <datosJugador>
                <fechaNac dia="9" mes="07" year="1997"></fechaNac>
                <altura>
                    1.91
                </altura>
                <ciudad>
                    Gijón
                </ciudad>
                <foto ruta="https://res.cloudinary.com/asw2122/image/upload/v1655033211/sew2122/rivera.jpg"></foto>
            </datosJugador>
            <equipo>
                <datosEquipo>
                    <nombre>
                        Girona F. C.
                    </nombre>
                    <fechas>
                        <fechaIni dia="29" mes="07" year="2020"></fechaIni>
                        <fechaFin dia="30" mes="12" year="2021"></fechaFin>
                    </fechas>
                    <antiguedad>
                        1930
                    </antiguedad>
                    <ciudad>
                        Gerona
                    </ciudad>
                </datosEquipo>
            </equipo>
            <equipo>
                <datosEquipo>
                    <nombre>
                        C. D. Leganés
                    </nombre>
                    <fechas>
                        <fechaIni dia="30" mes="06" year="2019"></fechaIni>
                        <fechaFin dia="09" mes="07" year="2020"></fechaFin>
                    </fechas>
                    <antiguedad>
                        1928
                    </antiguedad>
                    <ciudad>
                        Leganés
                    </ciudad>
                </datosEquipo>
            </equipo>
        </jugador>
        <jugador nombre="Francisco José" apellidos="Villalba Rodrigo" edad="24">
            <datosJugador>
                <fechaNac dia="11" mes="05" year="1998"></fechaNac>
                <altura>
                    1.70
                </altura>
                <ciudad>
                    Valencia
                </ciudad>
                <foto ruta="https://res.cloudinary.com/asw2122/image/upload/v1655033211/sew2122/villalba.jpg"></foto>
            </datosJugador>
            <equipo>
                <datosEquipo>
                    <nombre>
                        U. D. Almería
                    </nombre>
                    <fechas>
                        <fechaIni dia="28" mes="07" year="2020"></fechaIni>
                        <fechaFin dia="02" mes="07" year="2021"></fechaFin>
                    </fechas>
                    <antiguedad>
                        1989
                    </antiguedad>
                    <ciudad>
                        Almería
                    </ciudad>
                </datosEquipo>
            </equipo>
            <equipo>
                <datosEquipo>
                    <nombre>
                        Birmingham City F. C.
                    </nombre>
                    <fechas>
                        <fechaIni dia="10" mes="06" year="2019"></fechaIni>
                        <fechaFin dia="04" mes="07" year="2020"></fechaFin>
                    </fechas>
                    <antiguedad>
                        1875
                    </antiguedad>
                    <ciudad>
                        Birmingham
                    </ciudad>
                </datosEquipo>
            </equipo>
        </jugador>
        <jugador nombre="Gaspar" apellidos="Campos-Ansó Fernández" edad="22">
            <datosJugador>
                <fechaNac dia="27" mes="03" year="2000"></fechaNac>
                <altura>
                    1.75
                </altura>
                <ciudad>
